### ISSUE TITLE
How to get states of window contact sensors?

### ISSUE THREAD

**Issue by RPaschotta** [Pigotka/ha-cc-jablotron-cloud#10]
Window contact sensors have been mentioned under "Supported functionality", but in a quite unclear way. I got the integration working and now see the PG outputs, but nothing concerning window contact sensors. I would have hoped to find one sensor entity for each window in HA.

**Comment by Pigotka** [comment]
You can ask you jablotron provider to create PG for every sensor representing the state if they did do it initially. Window sensor state is otherwise hidden information.

**Comment by RPaschotta** [comment]
Thank you very much for the prompt answer, but I do not understand: There seem to be PG outputs, but I need inputs for the window contact sensors. Are you saying this is not possible? Or can one somehow associate the window contacts with the PG stuff to read it out in the integration? But we have only 10 PG outputs and more than 10 window contacts.
