### ISSUE TITLE
Devices unavailable 

### ISSUE THREAD

**Issue by rampie** [Pigotka/ha-cc-jablotron-cloud#13]
Hello,

I’m using this integration in few automations but I frequently receive the status unavailable from several components. Is this a know issue or do I have to adjust polling intervals or something?

Controlling the sections/zones are no problem. Just if I want to check for the current state, it tells me it’s unavailable…
kind regards.

**Comment by Pigotka** [comment]
Hi, thank you for your comment. I experiencing same but I'm still trying to narrow it down whether it is due to Jablotron servers are unavailable for some time or session is expiring.

But for sure their server are on maintanance sometimes during night and it can't be entirely avoided.

**Comment by rampie** [comment]
It isn’t just by night, it happens over the entire day….

Let me know if you find a way… or a method to use the latest known state in automations when when the current state is unavailable 😉

**Comment by Pigotka** [comment]
@rampie but what you posted just now it's different issue, just ask integration to recofigure or restart it should help you. What I was talking about looks different and will not last for 12h ;)

**Comment by Pigotka** [comment]
Yours can be connected with recent License changes or API upgrate addresed in recent release.

**Comment by rampie** [comment]
Installed the latest version last night and I dont have any pop-up to accept the new license when I log in so..

**Comment by Pigotka** [comment]
The popup is on jablotron cloud. You need to login there in web browser.

**Comment by rampie** [comment]
I did log in via web browser on Jablotron cloud 😉

**Comment by Pigotka** [comment]
It's not a popup it's just a message you need to agree with. But regardless the issue is the same as in #11 and it was resolved unless you will provide more info updating and accepting terms should solve this.
