### ISSUE TITLE
Can't login after update to 0.5.4

### ISSUE THREAD

**Issue by zeratul021** [Pigotka/ha-cc-jablotron-cloud#16]
Update via HACS, had to drop the integration and add it again. Now it doesn't accept my email/password. I am getting "Invalid authentication" error. Verified the credentials work on https://www.jablonet.net/ and in my mobile app. I can see ony this in ha log:
`2023-11-21 21:34:23.545 ERROR (ThreadPoolExecutor-9_0) [custom_components.jablotron100] State packet of unknown device (device 3): 55088075c000518b5609
`

**Comment by Pigotka** [comment]
I'm sorry but this is not related to this integration. The error you are having is from Jablotron100 not this one.

**Comment by zeratul021** [comment]
@Pigotka I am sorry for brevity on my part. The error message is indeed from Jablotron100, my bad, there wasn't anything else wehn searching for **jabl**.
However, the login still doesn't work for me in Jablotron Cloud integration. Any help on how to debug this? I validated the JSON sent to server contains correct credentials. Still, **Invalid authentication** error is returned every time.

**Comment by Pigotka** [comment]
You mentioned that it happend after you updated to new release. You can try to go back to older one and verify it won't help. I suspect unfortunately your local issue. Maybe HA installation is corupted.
