### ISSUE TITLE
Jablotron communication stops during the night, USB in sleep mode (proxmox server)?

### ISSUE THREAD

**Issue by RGB666** [Pigotka/ha-cc-jablotron-cloud#22]
It looks like my Jablotron-HA communication stops during the night. As all other HA communication have no problems during the night and the Jablotron is connected by a USB port, I have the feeling the USB port goes into a sort of standby/sleep/hibernation mode.
I am running HA on a proxmox server. Who can help me debugging my system? How can I check /ebug the USB port communication settings?

**Comment by Pigotka** [comment]
This integration does not support USB connection. I guess you are using another integration. This one is cloud based.

**Comment by RGB666** [comment]
Sorry!!!. I'm going to install the cloud integration directly to test if this works better then the usb integration!
