### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'json'

### ISSUE THREAD

**Issue by FilemonCZ** [Pigotka/ha-cc-jablotron-cloud#23]
Hello,

I have installed HA for my good friend and he has Jablotron 100 device, but i am getting this error - Failed setup, will retry: 'dict' object has no attribute 'json'. Name and password is correct because in web browser i can login. Could you please advise how can i fix it for him? Thank you Roman

Please see details from log

Logger: jablotronpy.jablotronpy
Source: /usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py:74
First occurred: 09:27:57 (13 occurrences)
Last logged: 09:29:03
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '2822fecb3eea462d9fdd4486baac85a1'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"2822fecb3eea462d9fdd4486baac85a1"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': 'c354d8fbd20c4ef7af92094e349dfbb2'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"c354d8fbd20c4ef7af92094e349dfbb2"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '71ad634b4bc347188fed5026735197e7'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"71ad634b4bc347188fed5026735197e7"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '5fc92aeff37248eca664bcfb5c5e01a1'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"5fc92aeff37248eca664bcfb5c5e01a1"}
An unexpected error occurred, status code: 404, response: {'http-code': 404, 'errors': [{'code': 'FUNCTION.NOT-FOUND', 'message': ''}], 'meta': {'display-type': 'TOAST'}, 'sentry-error-id': '1d19f01968654db18ff83c718de0a5ea'}, {"http-code":404,"errors":[{"code":"FUNCTION.NOT-FOUND","message":""}],"meta":{"display-type":"TOAST"},"sentry-error-id":"1d19f01968654db18ff83c718de0a5ea"}
Logger: homeassistant.backports.enum
Source: helpers/deprecation.py:197
First occurred: 09:27:52 (1 occurrences)
Last logged: 09:27:52
StrEnum was used from jablotron_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'jablotron_cloud' custom integration
This error originated from a custom integration.
Logger: custom_components.jablotron_cloud
Source: helpers/update_coordinator.py:354
integration: Jablotron Cloud (documentation, issues)
First occurred: 09:28:04 (3 occurrences)
Last logged: 09:28:38
Unexpected error fetching Jablotron Cloud data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/jablotron_cloud/init.py", line 135, in _async_update_data
gates = await self.hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 264, in get_programmable_gates
status, data = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 83, in _make_request
return self._make_request(end_point=end_point, headers=headers, payload=payload, retry=retry)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/jablotronpy/jablotronpy.py", line 77, in _make_request
logger.error(f"Exhausted all retry options, response: {data.json()}")
^^^^^^^^^
AttributeError: 'dict' object has no attribute 'json'

<img width="822" alt="Screenshot 2024-09-01 at 21 53 22" src="https://github.com/user-attachments/assets/7fc62c9a-df4a-4370-94a8-cb6eaabfb7a0">

**Comment by Pigotka** [comment]
Commented in original ticket in jablotronpy. Integration is handlig the failure correctly.
