### ISSUE TITLE
Entities do not show up with multiple connected homes

### ISSUE THREAD

**Issue by zoezoevp** [Pigotka/ha-cc-jablotron-cloud#3]
Hi,
I tried your custom integration and everything seems to be fine but I don't have any entities being created.  I do have 2 homes connected in my account.  When I log into the Jablotron portal, I need to select a home first before accessing the panels and sections.  Could this be related?

**Comment by lordzid** [comment]
I have the same situation

**Comment by Pigotka** [comment]
Integration should create separate Devices per each home. But I never teste this scenario localy as I don't have two homes. 
Can you try to enable debug loggin on the integration and check for the errors in the log please?

**Comment by Pigotka** [comment]
@fdegier Can you take a look? It originates in your library.

**Comment by fdegier** [comment]
@michalrentka did you ever log in with this user and accept the terms and conditions?

**Comment by michalrentka** [comment]
@fdegier if you mean log in to https://www.jablonet.net, then I logged in before and I can also log in now and I don't get any terms & conditions prompt. I guess I accepted it when I logged in the first time (which is before I tried this integration), I don't remember that. I'm checking the website and I don't see anything else to accept there.

**Comment by michalrentka** [comment]
@fdegier, @Pigotka I updated Home Assistant, HACS and wanted to give this another try. I enabled debug logging and reloaded the integration, I'm now getting:
```
2023-04-09 11:02:41.135 DEBUG (MainThread) [custom_components.jablotron_cloud] Preparing Jablotron data update coordinator
2023-04-09 11:02:44.452 DEBUG (MainThread) [custom_components.jablotron_cloud] Finished fetching Jablotron data in 3.317 seconds (success: True)
```

But nothing shows up anyway.

**Comment by michalrentka** [comment]
@Pigotka I updated and gave it a few tries. Unfortunately I still don't see any devices or entities. But this time logs seem good:

```
2023-04-12 18:19:49.509 DEBUG (MainThread) [custom_components.jablotron_cloud] Preparing Jablotron data update coordinator
2023-04-12 18:19:52.865 DEBUG (MainThread) [custom_components.jablotron_cloud] Finished fetching Jablotron data in 3.356 seconds (success: True)
```

So no idea what's wrong. I don't see anything else jablotron-related in logs.

**Comment by JHurme84** [comment]
> @Pigotka I updated and gave it a few tries. Unfortunately I still don't see any devices or entities. But this time logs seem good:
> 
> ```
> 2023-04-12 18:19:49.509 DEBUG (MainThread) [custom_components.jablotron_cloud] Preparing Jablotron data update coordinator
> 2023-04-12 18:19:52.865 DEBUG (MainThread) [custom_components.jablotron_cloud] Finished fetching Jablotron data in 3.356 seconds (success: True)
> ```
> 
> So no idea what's wrong. I don't see anything else jablotron-related in logs.

I have the same issue. Fresh installation and no devices or entities showing up.
Here are my only logs related:

2023-04-12 21:04:21.089 DEBUG (MainThread) [custom_components.jablotron_cloud] Preparing Jablotron data update coordinator
2023-04-12 21:04:25.499 DEBUG (MainThread) [custom_components.jablotron_cloud] Finished fetching Jablotron data in 4.409 seconds (success: True)

**Comment by dartapt** [comment]
Same problem.
Do not show me any device

**Comment by Nick75wien** [comment]
same here !

**Comment by Pigotka** [comment]
Recommend trying new version 0.5. We had an issue with homes without gates that cased problem discovering entities.

**Comment by zoezoevp** [comment]
testing v0.5 now and it seems to work.  I can see the two homes and their sections. thx!

**Comment by Pigotka** [comment]
Oh wow better then expected.
