### ISSUE TITLE
Jablotron Cloud Entities states are not available since HA Core 2024.11

### ISSUE THREAD

**Issue by DaRockwilder187** [Pigotka/ha-cc-jablotron-cloud#30]
Hello, 

since the update of HA Core 2024.11 the states of the entities are unkown. 
It is possible to change armed states (home, armed, unarmed) but the current state won't show in HA. 

Therefore automations based on armed state are not working anymore. 

I'm not sure if this log entry helps or is connected with this issue, since it says HA Core 2025.11 (will stop working):

____________

Logger: homeassistant.components.alarm_control_panel
Quelle: components/alarm_control_panel/__init__.py:210
Integration: Alarmzentrale (Dokumentation, Probleme)
Erstmals aufgetreten: 01:41:37 (6 Vorkommnisse)
Zuletzt protokolliert: 08:38:06

Entity alarm_control_panel.jablotron_feuer (<class 'custom_components.jablotron_cloud.alarm_control_panel.JablotronAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
Entity alarm_control_panel.jablotron_haus (<class 'custom_components.jablotron_cloud.alarm_control_panel.JablotronAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

_______________

Logger: homeassistant.const
Quelle: helpers/deprecation.py:222
Erstmals aufgetreten: 01:40:19 (11 Vorkommnisse)
Zuletzt protokolliert: 01:41:35

STATE_ALARM_ARMED_HOME was used from jablotron_cloud, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'jablotron_cloud' custom integration
STATE_ALARM_ARMING was used from jablotron_cloud, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMING instead, please report it to the author of the 'jablotron_cloud' custom integration
STATE_ALARM_DISARMED was used from jablotron_cloud, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'jablotron_cloud' custom integration
STATE_ALARM_DISARMING was used from jablotron_cloud, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMING instead, please report it to the author of the 'jablotron_cloud' custom integration
TEMP_CELSIUS was used from jablotron_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'jablotron_cloud' custom integration

Thank you and BR
Andreas

**Comment by Koky05** [comment]
It works, but it is necessary to manual refresh integration. I think they change way of refreshing configuration entity.

**Comment by karelkryda** [comment]
@Koky05 how exactly should I reload the integration?

I tried clicking the `reload` button under the integration, but unfortunately that didn't help.
![Screenshot_20241107_101813_Home Assistant.jpg](https://github.com/user-attachments/assets/705cceb3-f799-4a67-b6c3-ec97065725c8)

**Comment by DaRockwilder187** [comment]
For me it didn't work either. Did a complete new installation of the integration (delete device/entities and integration from HACS, re-downloaded, and setup new). 
same issue

**Comment by Koky05** [comment]
"Reload" option in your case.

For example I use three thermostats. two outside (one in dog house and one on side of house) and both works continously and reports temperature every 5 minutes at least:
![image](https://github.com/user-attachments/assets/b68731ce-91ff-4800-a87a-a5b91cf4feaa)


Then I have one inside at that one stop working or show same temperature for last 4 hours:
![image](https://github.com/user-attachments/assets/416b75e2-d7e2-4857-a077-7f8fab19baac)

**Comment by DaRockwilder187** [comment]
What do you mean by "reload"? I reloaded the integration like @karelkryda, but didn't make any change.

**Comment by Koky05** [comment]
In my case "Reload" helps and bring back statuses for every entity. Also like my pictures show thermometers works correctly.

**Comment by Koky05** [comment]
No we are on same topic, I have 15 PG and 15 sections, all of them after reload show current status (PG - Active / Inactive, Section - Arm / Disarm).

**Comment by DaRockwilder187** [comment]
Ok sorry, wasn't aware of temperature sensors in jablotron. 
Then let me ask you again, what do you mean with reload? where or how should I reload the entities?
This doesn't help:
![Screenshot 2024-11-07 130434](https://github.com/user-attachments/assets/80ed27ce-9646-4126-92c9-1e10dbfb38d8)
Thanks

**Comment by karelkryda** [comment]
In my integration, I only have alarm entities, not temperature sensors or other PG devices. 

For myself, I can say that restarting the home assistant container or reloading the integration will not solve the problem.

The logs do not show any errors, only a warning about the obsolescence of text states and a request to migrate to an internal enums in HA.

Logically, I assume that the default state of integration entities is the `unknown` state until the data is loaded from the Jablotron API.
Although I don't see an error about this behavior anywhere (as described in the second issue), it is possible that the behavior of the alarm component in HA has been modified in the latest release.

It seems to me that the property `state` [has been replaced](https://github.com/home-assistant/developers.home-assistant/commit/ab02bc1e01dce2baa6d145e4bc016d8247595dbe) by the property `alarm_state` and therefore this integration is no longer able to set the status correctly - or rather, it sets the wrong property.

In my opinion, it is necessary to replace this property name in [these lines of code](https://github.com/Pigotka/ha-cc-jablotron-cloud/blob/main/custom_components/jablotron_cloud/alarm_control_panel.py#L165-L217).

**Comment by Koky05** [comment]
Yes, for future support it will be neccesary to repair it, but it works only values are different:
![image](https://github.com/user-attachments/assets/ede006e6-73cf-494d-96bd-92f6ae886282)

**Comment by karelkryda** [comment]
It is not true that it would work in its current state. From your screenshot you can see that your alarm entities are also marked as unavailable, which I assume is the same problem as we have now.

**Comment by Koky05** [comment]
@karelkryda you have right, I see now your point of view. I use only PG from HA to control state of my house (open window, movement in house, etc...) so I take it as working integration.

**Comment by karelkryda** [comment]
I tried the modification I described above and it solved the problem. I'll open a PR fixing this and a few other deprecation errors in a moment.

![image](https://github.com/user-attachments/assets/531923a9-160d-4e0e-9c97-1ee23121a334)

**Comment by DaRockwilder187** [comment]
@karelkryda Best man!
#31 works for me, thank you very much! 
States are shown correctly and automation works again.

![image](https://github.com/user-attachments/assets/96ebbc2d-0d4e-4b1e-9128-f62b8f004a05)

**Comment by Faasteer** [comment]
Oh, great. Just noticed this issue that's blocking some of my automation and I see you're already working on it. Thanks for that. 👍

**Comment by maarten117** [comment]
> I tried the modification I described above and it solved the problem. I'll open a PR fixing this and a few other deprecation errors in a moment.
> 
> ![image](https://private-user-images.githubusercontent.com/59953812/384094658-531923a9-160d-4e0e-9c97-1ee23121a334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjY5MTUsIm5iZiI6MTczMTY2NjYxNSwicGF0aCI6Ii81OTk1MzgxMi8zODQwOTQ2NTgtNTMxOTIzYTktMTYwZC00ZTBlLTljOTctMWVlMjMxMjFhMzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEwMzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDQ3ZTZiMWE3NjUzZDUzZDQ1YjA2NTgzNjc0YmY3ZTQzYTc1MjQzODQ2MDI5NjAzZTUxMjExMWZmODk0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oPGWYxtjjsgCztu-U_K0mQe_aFDLQND7QpNeU5ozniw)

This did the trick, thanks.

**Comment by maarten117** [comment]
> Unfortunately, my skills are probably low because I don't know how to fix it accordingly. So I'm waiting for the official update. Hopefully it will come out soon, it's making my life a bit more complicated with my smart home.

I downloaded the modified files en replaced them in Home Assistant using the File editor.

**Comment by DaRockwilder187** [comment]
> > > I tried the modification I described above and it solved the problem. I'll open a PR fixing this and a few other deprecation errors in a moment.
> > > ![image](https://private-user-images.githubusercontent.com/59953812/384094658-531923a9-160d-4e0e-9c97-1ee23121a334.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjY5MTUsIm5iZiI6MTczMTY2NjYxNSwicGF0aCI6Ii81OTk1MzgxMi8zODQwOTQ2NTgtNTMxOTIzYTktMTYwZC00ZTBlLTljOTctMWVlMjMxMjFhMzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEwMzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDQ3ZTZiMWE3NjUzZDUzZDQ1YjA2NTgzNjc0YmY3ZTQzYTc1MjQzODQ2MDI5NjAzZTUxMjExMWZmODk0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oPGWYxtjjsgCztu-U_K0mQe_aFDLQND7QpNeU5ozniw)
> > 
> > 
> > This did the trick, thanks.
> 
> Unfortunately, my skills are probably low because I don't know how to fix it accordingly. So I'm waiting for the official update. Hopefully it will come out soon, it's making my life a bit more complicated with my smart home.

You need to download replace these files on you HA via File Editor
![image](https://github.com/user-attachments/assets/bf81b372-c450-428b-a700-0db616efae8f)

**Comment by Pigotka** [comment]
This was resolved in HA 24.11.2
