### ISSUE TITLE
NL language

### ISSUE THREAD

**Issue by maarten117** [Pigotka/ha-cc-jablotron-cloud#32]
I edited the en.json to an nl.json.
How to upload/participate?
[nl.json](https://github.com/user-attachments/files/17774177/nl.json)

**Comment by Pigotka** [comment]
Create PR into the main branch. If you do not know how let me know I will push it myself.

**Comment by maarten117** [comment]
That is beyond my capabilities at this moment :).

I will try to learn this.

In the mean time, the nl language JSON is attached to my previous post.

**Comment by Pigotka** [comment]
@maarten117 added in 0.6.5 release. Test it and report back. 
Thank you for contributing.

**Comment by maarten117** [comment]
Seems to be working.
YW.
