### ISSUE TITLE
Activating the PANIC Alarm from HA 

### ISSUE THREAD

**Issue by overflywingo** [Pigotka/ha-cc-jablotron-cloud#7]
Is this possible ? And if so, how ?
If not possible, perhaps a good option to add ... if feasible 

Thanks

**Comment by Pigotka** [comment]
What do mean by PANIC? Do you just want integration to trigger alarm state?

**Comment by overflywingo** [comment]
I want to have an integration to activate immediately the alarm, not to arm or disarm the alarm (this is already OK), but to make it ringing loudly (internal & external sirens).  In Jablotron terminology they're talking about "PANIC ALARM"

**Comment by Pigotka** [comment]
This is already possible using PG's. I have PG which triggers PANIC in Jablotron and integration controlls the PG. PANIC is always triggered by change in PG (sensor) in the house.

**Comment by overflywingo** [comment]
Thank you very much, I'll investigate further with PG triggers.  I already had a look, but can't find how PG can **activate** Panic.  I just saw that it's possible to define how PG are **reacting** after a Panic trigger.
