### ISSUE TITLE
Unable to complete setup - stuck in HA at "starting configuration wizzard"

### ISSUE THREAD

**Issue by hansgnom** [Pigotka/ha-cc-jablotron-cloud#8]
Hi All

I am very happy to see a possiblity to integrate jablotron into my home assistant. I have added Jablotron Cloud in HACS and tried to add the integration in HA. When I select it from the list of integrations it unfortunatley does not work. It gets stuck before the very fist screen loads. See this screenshot:
 
![image](https://github.com/Pigotka/ha-cc-jablotron-cloud/assets/76563892/2681be56-a38a-446e-b03b-251c97e06faf)

any suggestions?

**Comment by hansgnom** [comment]
after several restarts it is now working! sorry for that 😊

**Comment by macoch13** [comment]
Could you please describe more detailed what and how you restarted? I am not able to make it run

**Comment by Pigotka** [comment]
new version fixes data coordinator issues
