### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by pijix** [Pigotka/ha-cc-jablotron-cloud#9]
Hello, first of all thank's for your job.

I was able to install the integration and enter the credentials correctly without problems. But there is no way to show the devices and identities. Some help?

![image](https://github.com/Pigotka/ha-cc-jablotron-cloud/assets/1692640/936d69d7-6442-4b64-9e96-e8e94a9c0354)

**Comment by Pigotka** [comment]
It looks like it works just fine. Makes me a bit puzzled what could be the problem. But to make sure could you provide output of get_services()? This is the main entry point which created device in the integration. What you printed is I think get_sections which is nice but only used if we have actually the device.

**Comment by Pigotka** [comment]
Right, everything is alsmost equal as with my own alarm. I have no clue why your installation does not see any devices at all. I'm planing to add more logs to be able to debug another issue in next release so then we can resurect this. But it will take some time as I'm currently quite overloaded.

**Comment by Pigotka** [comment]
I also don't have any thermo devices and I see no problem. It returns empy response and this is ok.
What do you get as return value for get_thermo_devices ? Any error?

**Comment by Pigotka** [comment]
Alright. This helps a lot. I epxected that every call behaves the same but I never tried to test get_programmable_gates without gates. I checked the code in the meaintime and I see several problems connected with incorrect error handling. Will fix it soon.
Thanks for your help.

**Comment by Nick75wien** [comment]
I discover the same issue! Also I don't have any entities - where can I find the debug once enabled ?

**Comment by Pigotka** [comment]
Possible fix in latest 0.5.0 release. Please @pijix  try and report here. Thanks

**Comment by pkopiste** [comment]
> Hi! Installed and works fine!! Thank you!

same here - now ok - thank you!
